name: ci

on:
  pull_request:
  push:
    branches:
     - dev
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version:
            - 1.15.x
            - 1.16.x
      - name: Install CLI Dependencies
        run: |
          sudo apt-get -qq update && sudo apt-get install -y ldap-utils oathtool
          sudo apt-get -qq update && sudo apt-get install -y go-bindata
      - name: Make Bindata
        run: make bindata
      - name: Fetch Go dependencies
        run: go get -t -v ./...
      - name: Fail if a .go file hasn't been formatted with 'go fmt'
        run: diff -u <(echo -n) <(gofmt -d ./)
      - name: Full compile test
        run: make all
      - name: Output hashes to the build log
        run: cat bin/*.sha256
      - name: Integration test with compiled binary
        run: make test
